name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 18 * * *" # Runs daily at 6 PM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Profile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: OliverRhyme

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update 3D contribution calendar"
          git push